# Generated by Django 3.1.2 on 2021-04-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=150)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_name', models.CharField(max_length=30)),
                ('tourist_latitude', models.FloatField(null=True)),
                ('tourist_longitude', models.FloatField(null=True)),
                ('tourist_location', models.CharField(max_length=50)),
            ],
        ),
    ]
