# Generated by Django 3.1.2 on 2021-04-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='touristcon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locapp.tourist'),
            preserve_default=False,
        ),
    ]
