# Generated by Django 3.1.2 on 2021-04-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0002_destination_touristcon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='touristcon',
        ),
    ]
