# Generated by Django 3.1.2 on 2021-04-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0003_remove_destination_touristcon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinationImage', models.ImageField(blank=True, null=True, upload_to='destinationImages')),
                ('destination_desc', models.CharField(max_length=256)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locapp.destination')),
            ],
        ),
    ]
