# Generated by Django 3.1.2 on 2021-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0004_destinationdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationdetails',
            name='dest',
        ),
        migrations.AddField(
            model_name='destinationdetails',
            name='destination_extras',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinationdetails',
            name='destination_name',
            field=models.CharField(default='loc', max_length=50),
            preserve_default=False,
        ),
    ]
