# Generated by Django 3.1.2 on 2021-04-07 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0005_auto_20210405_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationMetaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_destination_name', models.CharField(max_length=60)),
                ('meta_destination_Image', models.ImageField(upload_to='metadestinationImages')),
                ('meta_destination_desc', models.CharField(max_length=256)),
                ('meta_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locapp.destinationdetails')),
            ],
        ),
    ]
